version: '3.8'
services:
  mongodb:
    image: mongo:latest
    env_file:
      - config.env
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    env_file:
      - config.env
    depends_on:
      - mongodb

volumes:
  mongodb_data_container:
